apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maps-pvc
  namespace: ats
spec:
  accessModes:
    - ReadWriteMany   # both viz-gateway and ats-env mount it
  resources:
    requests:
      storage: 500Mi
  # storageClassName: standard   # adjust for your cluster (e.g. nfs, longhorn)
